import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { StatusBar } from "expo-status-bar";

import { APP_NAME } from "@/src/constants";
import { useTheme } from "@/src/theme/ThemeProvider";
import { radius, spacing, typography } from "@/src/theme/tokens";

export default function PrivacyPolicy() {
  const { colors, scheme } = useTheme();
  return (
    <SafeAreaView
      style={[styles.root, { backgroundColor: colors.background }]}
      edges={["top", "left", "right", "bottom"]}
    >
      <StatusBar style={scheme === "dark" ? "light" : "dark"} />
      <View style={styles.header}>
        <Pressable
          testID="privacy-back-button"
          onPress={() => router.back()}
          style={[styles.iconBtn, { backgroundColor: colors.surface, borderColor: colors.outline }]}
        >
          <Ionicons name="chevron-back" size={22} color={colors.onSurface} />
        </Pressable>
        <Text style={[styles.title, { color: colors.onSurface }]}>Privacy Policy</Text>
        <View style={{ width: 44 }} />
      </View>

      <ScrollView contentContainerStyle={{ padding: spacing.lg, gap: spacing.md }}>
        <Text style={[styles.p, { color: colors.onSurface }]}>
          Last updated: 2026
        </Text>

        <Section title="1. About this policy" colors={colors}>
          This Privacy Policy describes how {APP_NAME} (the &ldquo;Application&rdquo;) handles information on
          your device. By installing or using the Application you accept the terms below. If you do not
          agree, please uninstall the Application.
        </Section>

        <Section title="2. Provided &quot;as is&quot;" colors={colors}>
          The Application is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis, without
          warranty of any kind, express or implied, including but not limited to fitness for a particular
          purpose or professional use.
        </Section>

        <Section title="3. No liability" colors={colors}>
          The developer/creator shall not be held responsible for any loss, damage, misuse, incorrect
          reports, missing information, or decisions taken on the basis of observations, annotations,
          location stamps or exports generated by the Application. The user assumes full responsibility
          for verifying every observation before relying on it for professional, safety, regulatory or
          commercial purposes.
        </Section>

        <Section title="4. User responsibility" colors={colors}>
          The user is solely responsible for the accuracy, lawfulness and completeness of any content
          captured, annotated, saved, exported or shared using the Application, and for compliance with
          all applicable laws, industry standards and organisational policies.
        </Section>

        <Section title="5. Data collection" colors={colors}>
          The Application does not intentionally collect, sell or share your personal information. No
          user data is transmitted to the developer. GPS coordinates are read from the device solely to
          generate the observation stamp on the image and are stored locally alongside the observation
          on your device.
        </Section>

        <Section title="6. On-device storage" colors={colors}>
          Photographs, annotations, GPS metadata, project details and settings created inside the
          Application are stored locally on your device and remain there unless you explicitly export
          or share them through the operating system share sheet. Deleting the Application will remove
          this data.
        </Section>

        <Section title="7. Permissions" colors={colors}>
          The Application may request access to the camera, photo library, location and biometric
          hardware. These permissions are used only for the corresponding on-device features and can be
          revoked at any time from your device settings.
        </Section>

        <Section title="8. Third-party services" colors={colors}>
          Reverse-geocoding is performed using the operating system&#39;s built-in geocoder. No
          additional third-party analytics, advertising or tracking SDKs are integrated.
        </Section>

        <Section title="9. Changes" colors={colors}>
          This policy may be updated from time to time. Continued use of the Application after any
          update constitutes acceptance of the revised terms.
        </Section>

        <Text style={[styles.footer, { color: colors.onSurfaceMuted }]}>
          Made by Nidamarthi Vinay Saketh
        </Text>
      </ScrollView>
    </SafeAreaView>
  );
}

function Section({
  title,
  children,
  colors,
}: {
  title: string;
  children: React.ReactNode;
  colors: any;
}) {
  return (
    <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.outline }]}>
      <Text style={[styles.h, { color: colors.onSurface }]}>{title}</Text>
      <Text style={[styles.p, { color: colors.onSurfaceMuted }]}>{children}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.md,
  },
  title: { ...typography.h2 },
  iconBtn: {
    width: 44,
    height: 44,
    borderRadius: radius.full,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  card: {
    borderWidth: 1,
    borderRadius: radius.md,
    padding: spacing.lg,
    gap: 6,
  },
  h: { fontSize: 15, fontWeight: "700" },
  p: { fontSize: 13, lineHeight: 20 },
  footer: { textAlign: "center", fontSize: 12, marginTop: spacing.lg },
});
